import tensorflow
import random
from sequence_annotation.data_handler.seq_dnn import *
from sequence_annotation.data_handler.fasta_handler import *
from keras.layers import Input,Dropout,Convolution1D,Flatten,MaxPooling1D,LSTM,Reshape,Activation
import keras
from keras.models import Model
from sequence_annotation.model.model_build_helper import CnnSettingCreator,tensor_end_with_terminal_binary_accuracy,tensor_end_with_terminal_binary_crossentropy
from sequence_annotation.model.sequence_annotation_model_factory import SeqAnnModelFactory
from sequence_annotation.model.model_trainer import ModelTrainer
import numpy



