import os
import pandas as pd
from argparse import ArgumentParser

def _get_name(path,with_postfix=False):
    rel_path = path.split('/')[-1]
    if with_postfix:
        return rel_path
    else:
        return rel_path.split('.')[0]

def main(data_root,saved_root,save_command_table_path,
         model_config_path,executor_config_path,appended_command=None):

    ROOT=os.path.abspath(os.path.dirname(__file__))
    COMMAND = "python3 {} -m {} -e {} -t {} -v {} -s {}"
    MAIN_PATH = '{}/train_model.py'.format(ROOT)
    paths = [MAIN_PATH,model_config_path,executor_config_path]

    for path in paths:
        if not os.path.exists(path):
            raise Exception("{} is not exists".format(path))
    
    saved_roots = []
    train_paths = []
    val_paths = []
    data_usage_path = os.path.join(data_root,'data_usage_path.csv')
    data_usage = pd.read_csv(data_usage_path,comment='#').to_dict('record')
    for item in data_usage:
        name = "{}_{}".format(_get_name(item['training_path']),_get_name(item['validation_path']))
        saved_path = os.path.join(saved_root,name)
        training_path = _get_name(item['training_path'],with_postfix=True)
        validation_path = _get_name(item['validation_path'],with_postfix=True)
        training_path = os.path.join(data_root,training_path)
        validation_path = os.path.join(data_root,validation_path)
        saved_roots.append(saved_path)
        train_paths.append(training_path)
        val_paths.append(validation_path)
        
    for paths in zip(train_paths,val_paths):
        if not all([os.path.exists(p) for p in paths]):
            raise Exception("Some paths, {}, are not exists".format(paths))
        
    with open(save_command_table_path,"w") as fp:
        fp.write("command\n")
            
        for paths in zip(train_paths,val_paths,saved_roots):
            train_path,val_path,saved_root = paths
            command = COMMAND.format(MAIN_PATH,model_config_path,executor_config_path,
                                     train_path,val_path,saved_root)
            if appended_command is not None:
                command += " "+appended_command
            command += "\n"
            fp.write(command)

if __name__ == '__main__':    
    parser = ArgumentParser()
    parser.add_argument("-d","--data_root",help='The data folder generated by batch_select_data.py',required=True)
    parser.add_argument("-s","--saved_root",required=True)
    parser.add_argument("-c","--save_command_table_path",required=True)
    parser.add_argument("-e","--executor_config_path",help="Path of Executor config",required=True)
    parser.add_argument("-m","--model_config_path",help="Path of Model config",required=True)
    parser.add_argument("--appended_command",type=str)
    
    args = parser.parse_args()
    kwargs = vars(args)
    main(**kwargs)
