from sequence_annotation.data_handler.json import read_json
from sequence_annotation.pipeline.pipeline_factory import PipelineFactory
from sequence_annotation.pipeline.batch_pipeline import BatchPipeline